<a href="https://colab.research.google.com/github/Amitda-an/Python-With-ML/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ood number print using normal method
for i in range (1,10):
  if i%2!=0:
    print(i)

[1]
[3]
[5]
[7]
[9]


In [ ]:
#comprehension law method
print([ i for i in range (1,11) if i%2!=0])

[1, 3, 5, 7, 9]


In [ ]:
print({i:i for i in range (1,11) if i%2!=0})

{1: 1, 3: 3, 5: 5, 7: 7, 9: 9}


PYTHON NUMPY

In [ ]:
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8,]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
x=np.arange(0,31,2) # printing 0 to 30 with 2 gap
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
x = x.reshape(4, 4)  # Reshape into a 4x4 matrix
x

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
o=np.linspace(0,4,5)
o

array([0., 1., 2., 3., 4.])

In [ ]:
o.resize(3,3)

In [ ]:
np.ones((3,2),int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((3,2),str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
y=np.array([4,5,6])
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [ ]:
np.vstack((p,2*p))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
p.T

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
p= p.astype('f')
p

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
r= np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
r[3,3:6]  #slicing

array([21, 22, 23])

In [ ]:
r[:2,:-4]

array([[0, 1],
       [6, 7]])

In [ ]:
r[:5,:-5]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24]])

In [ ]:
r[2:4,2:-1]

array([[14, 15, 16],
       [20, 21, 22]])

In [ ]:
r[r>30] = 30

In [ ]:
test=np.random.randint(0,10,(4,3))
test

array([[4, 0, 9],
       [9, 3, 1],
       [2, 8, 5],
       [4, 9, 3]])

In [ ]:
test=np.random.randint(1,10,4)
test

array([8, 4, 3, 8])

**QUESTIONS**

In [ ]:
#CREATE 3*3 NUMPY ARRAY OF ALL TUES'S (BOOLEAN)
a=np.bool_(np.ones((3,3)))
a

TypeError: Cannot interpret '3' as a data type

In [ ]:
test=np.arange(30)
for i in range test:


array([-1,  0,  0,  0,  0,  0, -1,  0])

In [ ]:
test=np.intersect1d([1,2,3,4,5],[1,3,5,7,9])
test

array([1, 3, 5])

In [ ]:
import numpy as np
rand_arr = np.random.random([5,3])
rand_arr

array([[0.82527544, 0.42496027, 0.52476854],
       [0.71571782, 0.3527688 , 0.24862581],
       [0.92724439, 0.58447587, 0.75501705],
       [0.26099706, 0.75683086, 0.49247226],
       [0.51185718, 0.77500054, 0.2342688 ]])

SyntaxError: invalid syntax (<ipython-input-7-15f0bab086ed>, line 1)